# ===== JavaScript =====
[[plugins]] # prettier
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'twig']
hook_add = '''
  nnoremap <Leader>p :Prettier<CR>
  let g:ale_fixers = {
  \  '*': ['remove_trailing_lines', 'trim_whitespace'],
  \  'javascript': ['eslint'],
  \}
'''

# ======================

# ===== Flutter =====
[[plugins]]
repo = 'reisub0/hot-reload.vim'
on_ft = ['dart']
# ====================

# ===== C# =====
[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs']
hook_add = '''
  let g:omnicomplete_fetch_full_documentation = 1
'''
# ====================
